server.port=8080
spring.application.name=farmconnect-backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5434/farmconnect_db
spring.datasource.username=farmuser
spring.datasource.password=farmpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT Configuration (Use a very long, random string in production, preferably from env vars)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A462D
# 15 minutes in milliseconds
app.jwt.expiration=900000
# 7 days in milliseconds
app.jwt.refresh-expiration=604800000

# Google OAuth2 Configuration
app.google.client-id=92679080519-1rdqvb2nb8n3qah2cgovutc2b3kh8bl9.apps.googleusercontent.com